"""Prometheus metrics definitions for telemetry and RAG evaluation."""
from prometheus_client import Counter, Histogram, Gauge

REQUEST_COUNT = Counter(
    "bisspecai_http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status_code"]
)

REQUEST_LATENCY = Histogram(
    "bisspecai_http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0]
)

LLM_GENERATION_TOKENS = Counter(
    "bisspecai_llm_tokens_generated_total",
    "Total tokens generated by LLM"
)

LLM_INFERENCE_LATENCY = Histogram(
    "bisspecai_llm_inference_duration_seconds",
    "LLM inference latency in seconds",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0]
)

VECTOR_SEARCH_LATENCY = Histogram(
    "bisspecai_vector_search_duration_seconds",
    "Vector search latency in seconds",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0]
)

GPU_VRAM_USAGE = Gauge(
    "bisspecai_gpu_vram_bytes",
    "GPU VRAM allocation in bytes"
)

GPU_TEMPERATURE = Gauge(
    "bisspecai_gpu_temperature_celsius",
    "GPU temperature in Celsius"
)

CACHE_HITS = Counter(
    "bisspecai_cache_hits_total",
    "Total semantic cache hits"
)

CACHE_MISSES = Counter(
    "bisspecai_cache_misses_total",
    "Total semantic cache misses"
)

RAG_CONTEXT_RELEVANCE = Gauge(
    "bisspecai_rag_context_relevance",
    "RAG Context Relevance Score"
)

RAG_GROUNDEDNESS = Gauge(
    "bisspecai_rag_groundedness",
    "RAG Groundedness Score"
)

RAG_ANSWER_RELEVANCE = Gauge(
    "bisspecai_rag_answer_relevance",
    "RAG Answer Relevance Score"
)
